# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('payment_month', models.IntegerField(blank=True, max_length=5)),
                ('amount_paid', models.IntegerField(blank=True, max_length=10)),
                ('rfid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Bill')),
            ],
        ),
    ]
