# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_balance', models.IntegerField(blank=True, max_length=10)),
                ('month', models.IntegerField(blank=True, max_length=5)),
                ('rfid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Payment')),
            ],
        ),
    ]
