# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20181109_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
