# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20181110_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
