# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20181110_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
