# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-23 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20181110_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='time',
        ),
    ]
